# Generated by Django 2.2.24 on 2022-01-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norteamericano_form', '0002_auto_20220124_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naextrainfo',
            name='na_rut',
            field=models.CharField(default='', help_text='Si es Pasaporte ingrese una P al inicio', max_length=21, unique=True, verbose_name='RUT/Pasaporte'),
        ),
    ]
