# Generated by Django 2.2.24 on 2022-03-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norteamericano_form', '0003_auto_20220125_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naextrainfo',
            options={'permissions': [('na_instructor_staff', 'instructor can enroll users and rerun courses')]},
        ),
    ]
